services:
    mongo:
        image: mongo
        restart: always
        # ports:
        #     - 27017:27017
        volumes:
            - ./docker-data/mongodb_data:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin

    local-server:
        build:
            context: .
            target: local-run
        ports:
            - 8000:8000
        volumes:
            - ./:/app/
        environment:
            - MONGODB_URI=mongodb://admin:admin@mongo:27017/

    remote-server:
        image: skrmain/expressjs-store-api:latest
        ports:
            - 8001:8000
        environment:
            - MONGODB_URI=mongodb://admin:admin@mongo:27017/
