services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./docker-data/mongodb_data:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
    server:
        build: .
        ports:
            - 8000:8000
        volumes:
            - ./:/app/
        environment:
            - MONGODB_URL=mongodb://admin:admin@mongo:27017/

