tags:
    - name: Auth
      description: Authentication API
    - name: Users
      description: Users API
    - name: Todos
      description: Todos API

paths:
    /register:
        post:
            tags:
                - Auth
            summary: Register User
            parameters:
                - name: body
                  in: body
                  description: User Email
                  required: true
                  schema:
                      $ref: '#/definitions/userRegisterModel'
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

    /login:
        post:
            tags:
                - Auth
            summary: Login Users
            parameters:
                - name: body
                  in: body
                  description: User Email
                  required: true
                  schema:
                      $ref: '#/definitions/userLoginModel'
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

    /token/refresh:
        post:
            tags:
                - Auth
            summary: Login Users
            parameters:
                - name: body
                  in: body
                  description: refresh token
                  required: true
                  schema:
                      type: object
                      required:
                          - email
                          - password
                      properties:
                          refresh:
                              - type: string
                              - description: Refresh Token
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

    /users/me:
        get:
            tags:
                - Users
            summary: Find User By Id
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

    /users/search:
        get:
            tags:
                - Users
            summary: Search User by username
            parameters:
                - name: username
                  in: query
                  description: user Id
                  required: true
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

    /todos:
        post:
            tags:
                - Todos
            summary: Delete User By Id
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

        get:
            tags:
                - Todos
            summary: List of User Todos
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

    /todos/{todoId}:
        get:
            tags:
                - Todos
            summary: Detail of a Todo
            parameters:
                - name: todoId
                  in: path
                  description: todo Id
                  required: true
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'
        patch:
            tags:
                - Todos
            summary: Update a Todo
            parameters:
                - name: todoId
                  in: path
                  description: todo Id
                  required: true
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'
        delete:
            tags:
                - Todos
            summary: Delete a Todo
            parameters:
                - name: todoId
                  in: path
                  description: todo Id
                  required: true
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

    /todos/{todoId}/users/{userId}/permissions:
        patch:
            tags:
                - Todos
            summary: Update Permissions of a todo for another User
            parameters:
                - name: todoId
                  in: path
                  description: todo Id
                  required: true
                - name: userId
                  in: path
                  description: user Id
                  required: true
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'
        delete:
            tags:
                - Todos
            summary: Remove all Permissions of a Todo from a User
            parameters:
                - name: todoId
                  in: path
                  description: todo Id
                  required: true
                - name: userId
                  in: path
                  description: user Id
                  required: true
            responses:
                200:
                    description: 'OK'
                500:
                    description: 'Server Error'

# definitions
definitions:
    userLoginModel:
        type: object
        required:
            - email
            - password
        properties:
            email:
                type: string
                description: User Email
            password:
                type: string
                description: User Account Password
    userRegisterModel:
        type: object
        required:
            - email
            - username
            - password
        properties:
            email:
                type: string
                description: User Email
            username:
                type: string
                description: Username
            password:
                type: string
                description: User Account Password
